//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.30 at 06:45:51 PM UTC 
//


package com.dronebuzzers.parts.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dronebuzzers.parts.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dronebuzzers.parts.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPartResponse }
     * 
     */
    public GetPartResponse createGetPartResponse() {
        return new GetPartResponse();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link GetPartRequest }
     * 
     */
    public GetPartRequest createGetPartRequest() {
        return new GetPartRequest();
    }

    /**
     * Create an instance of {@link GetPartsByTypeRequest }
     * 
     */
    public GetPartsByTypeRequest createGetPartsByTypeRequest() {
        return new GetPartsByTypeRequest();
    }

    /**
     * Create an instance of {@link GetPartsResponse }
     * 
     */
    public GetPartsResponse createGetPartsResponse() {
        return new GetPartsResponse();
    }

    /**
     * Create an instance of {@link PartList }
     * 
     */
    public PartList createPartList() {
        return new PartList();
    }

    /**
     * Create an instance of {@link GetPartsByTypeResponse }
     * 
     */
    public GetPartsByTypeResponse createGetPartsByTypeResponse() {
        return new GetPartsByTypeResponse();
    }

    /**
     * Create an instance of {@link GetPartsRequest }
     * 
     */
    public GetPartsRequest createGetPartsRequest() {
        return new GetPartsRequest();
    }

}
